### ISSUE TITLE
Reconcile with WICG polyfill?

### ISSUE THREAD

**Issue by RByers** [josh/event-listener-options-polyfill#4]
PRs happily accepted to the original polyfill: https://github.com/WICG/EventListenerOptions/blob/gh-pages/EventListenerOptions.polyfill.js

**Comment by josh** [comment]
Hey @RByers! Totally missed yours. I'm just going to shut this one down and try to help out on yours. Thanks!

**Comment by RByers** [comment]
Cool, thanks!  I didn't write that one either (@dtapuska did), and am not attached to any details there - feel free to propose major changes.  We have included links to that one in a bunch of our ELO outreach / documentation.
